# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='update_time',
            field=models.DateField(null=True),
        ),
    ]
