# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0002_auto_20171206_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='lang',
            field=models.CharField(choices=[('Arabic', 'AR'), ('Othor', 'OT')], default=('Arabic', 'AR'), max_length=3),
        ),
    ]
