# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0005_auto_20171214_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_cover',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
