# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0006_auto_20171215_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_cover',
            field=models.FileField(upload_to=''),
        ),
    ]
