# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0007_auto_20171218_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
    ]
