# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0008_remove_chapter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='update_time',
        ),
        migrations.AddField(
            model_name='story',
            name='update_time',
            field=models.DateField(null=True),
        ),
    ]
