# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0009_auto_20171223_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
