# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0010_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egamen.Story'),
        ),
    ]
