# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0011_auto_20171225_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.TextField(),
        ),
    ]
