# Generated by Django 2.0 on 2017-12-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0012_auto_20171226_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='lang',
            new_name='language',
        ),
    ]
