# Generated by Django 2.0 on 2018-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0015_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='guest_review',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
