# Generated by Django 2.0 on 2018-01-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0016_comments_guest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egamen.Story'),
        ),
    ]
