# Generated by Django 2.0 on 2018-01-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0017_comments_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egamen.Story'),
        ),
    ]
