# Generated by Django 2.0 on 2018-01-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egamen', '0022_auto_20180101_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
